### PR TITLE
New doc theme and docs fixes

### LINKED ISSUE #563: Use different documentation template
Current sphinx theme (https://robocop.readthedocs.io/en/latest/rules.html) could look better. For instance I find Robotidy documentation easier to read & our logo is well presented (https://robotidy.readthedocs.io/en/latest/index.html).

### PR DESCRIPTION
**Pull request by bhirsz**
Closes #563 

@mnojek please check it visually - I can modify pretty much everything through custom css (spacing, padding, colours etc). I switched from rtd theme to Sphinx default alabaster theme. You can build documentation locally with:
```
tox -e docs
```
Documentation will be under docs/_build/index.html

### CODE REVIEW

**Comment by mnojek** [comment]
In my opinion, this theme looks better than the previous one and is more readable. But I can see an issue on small screens (actually, my laptop has only 14") where the left menu is not properly displayed and even cannot be scrolled down. Here is the screenshot:
image
I needed to resize the page in browser to 80% to fully see the menu:
image
I wonder if other themes also have this problem.

**Comment by bhirsz** [comment]
@mnojek 

It's actually configurable - in conf.py remove ``"fixed_sidebar": True,`` and see the difference. On mobile it's always `False`. The problem that without that option the menu stays at the top of the page so with long page (like `rules`) you need to scroll way to the top. That of course could be workarounded with some custom css

**Comment by bhirsz** [comment]
This theme looks nice, and it have scrollable sidebar: https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

**Comment by mnojek** [comment]
Ok, with `"fixed_sidebar": True` it looks better but, yeah, now I need to scroll all the way up to see it. Nevertheless, I prefer this one, because it's the only one that makes it available for me :)
All in all, this theme looks better and I think we can use it.

**Review by mnojek — DISMISSED** [review]

**Comment by mnojek** [comment]
> This theme looks nice, and it have scrollable sidebar: https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

Didn't see this comment. Is it also available in sphinx?

**Comment by bhirsz** [comment]
> > This theme looks nice, and it have scrollable sidebar: https://setuptools.pypa.io/en/latest/userguide/package_discovery.html
> 
> Didn't see this comment. Is it also available in sphinx? Looks way more user-friendly with those dropdowns in menu and scrollable sidebar!

It's def build on sphinx, looks like https://github.com/pradyunsg/furo though I'm not sure if it's modified or used pure. I can try it out later (though robotidy uses alabaster so I need to think if I want to all our tools to use the same theme for consistent)

**Comment by bhirsz** [comment]
@mnojek 
Updated theme with furo theme. I also make some changes, for example I've added simple dropdowns where we had bit too much text:
image

image

Please check it out

**Comment by mnojek** [comment]
> Please check it out

This is just great! I love it!!! ❤️

**Review by mnojek — DISMISSED** [review]

**Comment by mnojek** [comment]
Now I see that there is no element in the menu that navigates to index.html (it's possible to click on the logo, but it's kind of hidden from the users).
Also, there is no visible link to GitHub repo and the badge with amount of stars.

**Comment by bhirsz** [comment]
@mnojek 
How bad is Github stars not centered?
image

I'm still fighthing with it - for now it's left aligned and it looks a bit..off. But it's very resistant to any attempt of moving it to center ;)

**Review by mnojek — APPROVED** [review]
That looks great!

**Pull request merged**
